apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo-devops-project
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: demo-devops-project
    spec:
      containers:
      - name: demo-devops-project
        image: nethasvs/demo-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
